#!/bin/bash
# ===========================================
#  Build script pour Netlify
#  Génère config.js à partir des variables
#  d'environnement configurées sur Netlify
# ===========================================

echo "🔧 Generating config.js from environment variables..."

cat > assets/js/config.js << EOF
/**
 * Auto-generated by build.sh — DO NOT EDIT
 * Les clés viennent des variables d'environnement Netlify
 */
const APP_CONFIG = {
  gemini: {
    apiKey: '${GEMINI_API_KEY}',
  },
  emailjs: {
    publicKey: '${EMAILJS_PUBLIC_KEY}',
    serviceId: '${EMAILJS_SERVICE_ID}',
    templateId: '${EMAILJS_TEMPLATE_ID}',
  }
};

const configReady = Promise.resolve();
console.log('✅ Configuration loaded');
EOF

echo "✅ config.js generated successfully!"
