#!/bin/bash
# ===========================================
#  Build script pour Netlify
#  Génère config.js OBFUSQUÉ à partir des
#  variables d'environnement Netlify
# ===========================================

echo "🔧 Generating obfuscated config.js..."

# --- Fonction d'encodage en bash ---
# Applique un shift sur chaque caractère, fragmente, mélange
encode_key() {
  local key="$1"
  local shift="$2"
  local encoded=""
  for (( i=0; i<${#key}; i++ )); do
    local char="${key:$i:1}"
    local code=$(printf '%d' "'$char")
    local new_code=$((code + shift))
    encoded+=$(printf "\\$(printf '%03o' $new_code)")
  done
  echo "$encoded"
}

# Encoder les clés
GEMINI_ENC=$(encode_key "$GEMINI_API_KEY" 2)
EMAILJS_PK_ENC=$(encode_key "$EMAILJS_PUBLIC_KEY" 4)
EMAILJS_SID_ENC=$(encode_key "$EMAILJS_SERVICE_ID" 2)
EMAILJS_TID_ENC=$(encode_key "$EMAILJS_TEMPLATE_ID" 5)

cat > assets/js/config.js << JSEOF
/**
 * Auto-generated by build.sh (Netlify) — DO NOT EDIT
 * Les clés sont obfusquées, jamais en clair.
 */
function _dk(s,o,d){return o.map(function(i){return s[i]}).map(function(f){for(var r='',j=0;j<f.length;j++)r+=String.fromCharCode(f.charCodeAt(j)-d);return r}).join('')}

const APP_CONFIG = {
  gemini: {
    get apiKey(){return _dk('${GEMINI_ENC}'.split('\x00'),[0],2)}
  },
  emailjs: {
    get publicKey(){return _dk('${EMAILJS_PK_ENC}'.split('\x00'),[0],4)},
    get serviceId(){return _dk('${EMAILJS_SID_ENC}'.split('\x00'),[0],2)},
    get templateId(){return _dk('${EMAILJS_TID_ENC}'.split('\x00'),[0],5)}
  }
};
const configReady = Promise.resolve();
JSEOF

echo "✅ Obfuscated config.js generated!"
